export interface Country {
  code: string
  name: string
  timezone: string
}

export const COUNTRIES: Country[] = [
  { code: 'DZ', name: 'Algeria', timezone: 'Africa/Algiers' },
  { code: 'AO', name: 'Angola', timezone: 'Africa/Lagos' },
  { code: 'AR', name: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
  { code: 'AM', name: 'Armenia', timezone: 'Asia/Yerevan' },
  { code: 'AU', name: 'Australia', timezone: 'Australia/Sydney' },
  { code: 'AT', name: 'Austria', timezone: 'Europe/Vienna' },
  { code: 'AZ', name: 'Azerbaijan', timezone: 'Asia/Baku' },
  { code: 'BH', name: 'Bahrain', timezone: 'Asia/Riyadh' },
  { code: 'BE', name: 'Belgium', timezone: 'Europe/Paris' },
  { code: 'BO', name: 'Bolivia', timezone: 'America/Caracas' },
  { code: 'BR', name: 'Brazil', timezone: 'America/Sao_Paulo' },
  { code: 'BG', name: 'Bulgaria', timezone: 'Europe/Athens' },
  { code: 'KH', name: 'Cambodia', timezone: 'Asia/Bangkok' },
  { code: 'CM', name: 'Cameroon', timezone: 'Africa/Lagos' },
  { code: 'CA', name: 'Canada', timezone: 'America/Toronto' },
  { code: 'CL', name: 'Chile', timezone: 'America/Santiago' },
  { code: 'CN', name: 'China', timezone: 'Asia/Shanghai' },
  { code: 'CO', name: 'Colombia', timezone: 'America/Bogota' },
  { code: 'HR', name: 'Croatia', timezone: 'Europe/Vienna' },
  { code: 'CZ', name: 'Czech Republic', timezone: 'Europe/Prague' },
  { code: 'DK', name: 'Denmark', timezone: 'Europe/Stockholm' },
  { code: 'EC', name: 'Ecuador', timezone: 'America/Bogota' },
  { code: 'EG', name: 'Egypt', timezone: 'Africa/Cairo' },
  { code: 'EE', name: 'Estonia', timezone: 'Europe/Helsinki' },
  { code: 'ET', name: 'Ethiopia', timezone: 'Africa/Addis_Ababa' },
  { code: 'FJ', name: 'Fiji', timezone: 'Pacific/Fiji' },
  { code: 'FI', name: 'Finland', timezone: 'Europe/Helsinki' },
  { code: 'FR', name: 'France', timezone: 'Europe/Paris' },
  { code: 'GE', name: 'Georgia', timezone: 'Asia/Tbilisi' },
  { code: 'DE', name: 'Germany', timezone: 'Europe/Berlin' },
  { code: 'GH', name: 'Ghana', timezone: 'Africa/Accra' },
  { code: 'GR', name: 'Greece', timezone: 'Europe/Athens' },
  { code: 'GT', name: 'Guatemala', timezone: 'America/Mexico_City' },
  { code: 'HK', name: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
  { code: 'HU', name: 'Hungary', timezone: 'Europe/Vienna' },
  { code: 'IS', name: 'Iceland', timezone: 'Europe/London' },
  { code: 'IN', name: 'India', timezone: 'Asia/Kolkata' },
  { code: 'ID', name: 'Indonesia', timezone: 'Asia/Jakarta' },
  { code: 'IR', name: 'Iran', timezone: 'Asia/Tehran' },
  { code: 'IQ', name: 'Iraq', timezone: 'Asia/Riyadh' },
  { code: 'IE', name: 'Ireland', timezone: 'Europe/Dublin' },
  { code: 'IL', name: 'Israel', timezone: 'Asia/Jerusalem' },
  { code: 'IT', name: 'Italy', timezone: 'Europe/Rome' },
  { code: 'JP', name: 'Japan', timezone: 'Asia/Tokyo' },
  { code: 'JO', name: 'Jordan', timezone: 'Asia/Jerusalem' },
  { code: 'KZ', name: 'Kazakhstan', timezone: 'Asia/Almaty' },
  { code: 'KE', name: 'Kenya', timezone: 'Africa/Nairobi' },
  { code: 'KW', name: 'Kuwait', timezone: 'Asia/Riyadh' },
  { code: 'LV', name: 'Latvia', timezone: 'Europe/Helsinki' },
  { code: 'LB', name: 'Lebanon', timezone: 'Asia/Jerusalem' },
  { code: 'LY', name: 'Libya', timezone: 'Africa/Cairo' },
  { code: 'LT', name: 'Lithuania', timezone: 'Europe/Helsinki' },
  { code: 'LU', name: 'Luxembourg', timezone: 'Europe/Paris' },
  { code: 'MY', name: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
  { code: 'MT', name: 'Malta', timezone: 'Europe/Rome' },
  { code: 'MX', name: 'Mexico', timezone: 'America/Mexico_City' },
  { code: 'MA', name: 'Morocco', timezone: 'Africa/Casablanca' },
  { code: 'NL', name: 'Netherlands', timezone: 'Europe/Amsterdam' },
  { code: 'NZ', name: 'New Zealand', timezone: 'Pacific/Auckland' },
  { code: 'NG', name: 'Nigeria', timezone: 'Africa/Lagos' },
  { code: 'NO', name: 'Norway', timezone: 'Europe/Oslo' },
  { code: 'OM', name: 'Oman', timezone: 'Asia/Dubai' },
  { code: 'PK', name: 'Pakistan', timezone: 'Asia/Karachi' },
  { code: 'PA', name: 'Panama', timezone: 'America/Bogota' },
  { code: 'PY', name: 'Paraguay', timezone: 'America/Santiago' },
  { code: 'PE', name: 'Peru', timezone: 'America/Lima' },
  { code: 'PH', name: 'Philippines', timezone: 'Asia/Manila' },
  { code: 'PL', name: 'Poland', timezone: 'Europe/Warsaw' },
  { code: 'PT', name: 'Portugal', timezone: 'Europe/Lisbon' },
  { code: 'QA', name: 'Qatar', timezone: 'Asia/Riyadh' },
  { code: 'RO', name: 'Romania', timezone: 'Europe/Bucharest' },
  { code: 'RU', name: 'Russia', timezone: 'Europe/Moscow' },
  { code: 'SA', name: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
  { code: 'RS', name: 'Serbia', timezone: 'Europe/Warsaw' },
  { code: 'SG', name: 'Singapore', timezone: 'Asia/Singapore' },
  { code: 'SK', name: 'Slovakia', timezone: 'Europe/Prague' },
  { code: 'SI', name: 'Slovenia', timezone: 'Europe/Vienna' },
  { code: 'ZA', name: 'South Africa', timezone: 'Africa/Johannesburg' },
  { code: 'KR', name: 'South Korea', timezone: 'Asia/Seoul' },
  { code: 'ES', name: 'Spain', timezone: 'Europe/Madrid' },
  { code: 'LK', name: 'Sri Lanka', timezone: 'Asia/Kolkata' },
  { code: 'SD', name: 'Sudan', timezone: 'Africa/Nairobi' },
  { code: 'SE', name: 'Sweden', timezone: 'Europe/Stockholm' },
  { code: 'CH', name: 'Switzerland', timezone: 'Europe/Berlin' },
  { code: 'SY', name: 'Syria', timezone: 'Asia/Jerusalem' },
  { code: 'TW', name: 'Taiwan', timezone: 'Asia/Taipei' },
  { code: 'TZ', name: 'Tanzania', timezone: 'Africa/Nairobi' },
  { code: 'TH', name: 'Thailand', timezone: 'Asia/Bangkok' },
  { code: 'TN', name: 'Tunisia', timezone: 'Africa/Algiers' },
  { code: 'TR', name: 'Turkey', timezone: 'Europe/Istanbul' },
  { code: 'UG', name: 'Uganda', timezone: 'Africa/Nairobi' },
  { code: 'UA', name: 'Ukraine', timezone: 'Europe/Kyiv' },
  { code: 'AE', name: 'United Arab Emirates', timezone: 'Asia/Dubai' },
  { code: 'GB', name: 'United Kingdom', timezone: 'Europe/London' },
  { code: 'US', name: 'United States', timezone: 'America/New_York' },
  { code: 'UY', name: 'Uruguay', timezone: 'America/Sao_Paulo' },
  { code: 'UZ', name: 'Uzbekistan', timezone: 'Asia/Tashkent' },
  { code: 'VE', name: 'Venezuela', timezone: 'America/Caracas' },
  { code: 'VN', name: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'YE', name: 'Yemen', timezone: 'Asia/Riyadh' },
  { code: 'ZW', name: 'Zimbabwe', timezone: 'Africa/Johannesburg' },
]
